# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 250)
        Login.setMinimumSize(QtCore.QSize(400, 259))
        Login.setMaximumSize(QtCore.QSize(438, 259))
        Login.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        with open('login_style.txt') as stylefile:
            style = stylefile.read()
        Login.setStyleSheet(style)
        self.iranyekanr = QtGui.QFontDatabase.addApplicationFont(
            "IRANYekanX_Regular.ttf")
        self.iranyekanb = QtGui.QFontDatabase.addApplicationFont(
            "IRANYekanX_Bold.ttf")
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gl_login = QtWidgets.QGridLayout()
        self.gl_login.setObjectName("gl_login")
        self.lnk_signup = QtWidgets.QCommandLinkButton(
            parent=self.centralwidget)
        self.lnk_signup.setLayoutDirection(
            QtCore.Qt.LayoutDirection.RightToLeft)
        self.lnk_signup.setAutoDefault(False)
        self.lnk_signup.setDefault(False)
        self.lnk_signup.setDescription("")
        self.lnk_signup.setObjectName("lnk_signup")
        self.gl_login.addWidget(self.lnk_signup, 5, 1, 1, 1)
        self.btn_sendlogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_sendlogin.setStyleSheet("QPushButton {\n"
                                         "  background-color: rgb(255, 179, 0);\n"
                                         "  color: #fff;\n"
                                         "  font-weight: 600;\n"
                                         "  border-radius: 8px;\n"
                                         "  border: 1px solid rgb(255, 179, 0);\n"
                                         "  padding: 5px 15px;\n"
                                         "  margin-top: 0px;\n"
                                         "  margin-bottom: 0px;\n"
                                         "  outline: 0px;\n"
                                         "  font: 10pt ;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover{\n"
                                         "  background-color: rgb(236, 118, 0);\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed{\n"
                                         "  background-color: rgb(255, 227, 82);\n"
                                         "  border-color:;\n"
                                         "  font-weight: 600;\n"
                                         "  border-radius: 8px;\n"
                                         "  border: 3px solid rgb(255, 170, 0);\n"
                                         "  padding: 5px 15px;\n"
                                         "  margin-top: 0px;\n"
                                         "  outline: 0px;\n"
                                         "  color: rgb(255, 170, 0);\n"
                                         "}")
        self.btn_sendlogin.setObjectName("btn_sendlogin")
        self.gl_login.addWidget(self.btn_sendlogin, 4, 0, 1, 3)
        self.txt_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_password.setObjectName("txt_password")
        self.gl_login.addWidget(self.txt_password, 3, 0, 1, 3)
        self.txt_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_username.setObjectName("txt_username")
        self.gl_login.addWidget(self.txt_username, 2, 0, 1, 3)
        self.lbl_login = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("IRANYekanX")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_login.setFont(font)
        self.lbl_login.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.lbl_login.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_login.setObjectName("lbl_login")
        self.gl_login.addWidget(self.lbl_login, 1, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gl_login, 0, 0, 1, 1)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)
        Login.setTabOrder(self.txt_username, self.txt_password)
        Login.setTabOrder(self.txt_password, self.btn_sendlogin)
        Login.setTabOrder(self.btn_sendlogin, self.lnk_signup)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "صفحه ورود"))
        self.lnk_signup.setText(_translate("Login", "ثبت کاربر جدید"))
        self.btn_sendlogin.setText(_translate("Login", "ورود"))
        self.txt_password.setPlaceholderText(_translate("Login", "رمز عبور"))
        self.txt_username.setPlaceholderText(_translate("Login", "نام کاربری"))
        self.lbl_login.setText(_translate("Login", "صفحه ورود"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
